version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hrms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root123}
      MYSQL_DATABASE: ${DB_NAME:-hrmgo_hero}
      MYSQL_USER: ${DB_USER:-hrms_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-hrms_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - hrms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # HRMS Application
  hrms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrms-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER:-hrms_user}
      DB_PASSWORD: ${DB_PASSWORD:-hrms_password}
      DB_NAME: ${DB_NAME:-hrmgo_hero}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      PORT: 8000
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000,http://localhost:5173}
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend/uploads:/app/src/backend/uploads
      - ./logs:/app/logs
    networks:
      - hrms-network
    command: >
      sh -c "
        echo 'Waiting for MySQL to be ready...' &&
        sleep 10 &&
        echo 'Running database setup...' &&
        node src/backend/setup-database.js &&
        echo 'Starting HRMS server...' &&
        node src/backend/server.js
      "

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: hrms-nginx
    restart: always
    depends_on:
      - hrms-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - hrms-network

volumes:
  mysql_data:
    driver: local

networks:
  hrms-network:
    driver: bridge
